-- File: tests/integration/destination-dirty.sql
--
-- Intentionally wrong schema used by the --drop-schema integration scenario.
-- The accounts table is missing the display_name column, orders has a stale
-- column that origin does not have, and there is an extra table that should
-- disappear after DROP SCHEMA ... CASCADE.
--
-- PostgresCopy must drop this entire schema and rebuild it from origin DDL
-- before the data copy can succeed.

create table public.accounts (
    id integer generated by default as identity primary key,
    email text not null,
    -- display_name is intentionally absent
    created_at timestamptz not null
);

create table public.orders (
    id integer generated by default as identity primary key,
    account_id integer not null references public.accounts(id),
    total_cents integer not null,
    note text,
    stale_column text  -- not present on origin; would break preflight without --drop-schema
);

-- Extra table that should vanish after DROP SCHEMA ... CASCADE.
create table public.legacy_junk (
    id integer primary key,
    data text
);
