create table public.accounts (
    id integer generated by default as identity primary key,
    email text not null,
    display_name text,
    created_at timestamptz not null
);

create table public.orders (
    id integer generated by default as identity primary key,
    account_id integer not null references public.accounts(id),
    total_cents integer not null,
    note text
);

insert into public.accounts (id, email, display_name, created_at) values
    (1, 'ada@example.com', 'Ada', '2026-04-30T08:00:00Z'),
    (2, 'grace@example.com', null, '2026-04-30T08:05:00Z');

insert into public.orders (id, account_id, total_cents, note) values
    (100, 1, 2499, 'first order'),
    (101, 1, 1299, null),
    (102, 2, 9900, 'gift');
